# Generated by Django 5.2.4 on 2025-07-28 12:25

import django.db.models.deletion
import scanner.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=scanner.models.user_normal_file_path)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=scanner.models.user_ocr_text_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('smart_scanned_file', models.ImageField(blank=True, null=True, upload_to=scanner.models.user_smart_scan_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.folder')),
            ],
            options={
                'unique_together': {('title', 'user')},
            },
        ),
    ]
